name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Android APK
        uses: khushit-shah/pwa-to-apk@v0.1.2
        with:
          url: https://fuesiclear-cpu.github.io/
          name: MyWebProject

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Android-App
          path: ./*.apk
